name: Build and Test with deps
on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
      - name: Checkout vgura
        uses: actions/checkout@v2
        with:
          path: vgura
      - name: Build V
        run: |
          make
          sudo ./v symlink
      - name: V doctor
        run: v doctor
      - name: Move vgura source code to V Modules
        run: mv ./vgura ~/.vmodules/gura
      - name: Execute Tests
        run: ~/.vmodules/gura/bin/test
