name: Deploy Documentation

on:
  push:
    branches:
      - master

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout VSL
        uses: actions/checkout@v2
        with:
          path: gura

      - name: Setup V
        uses: vlang/setup-v@v1
        with:
          check-latest: true

      - name: V doctor
        run: v doctor

      - name: Build docs
        run: |
          rm -f ./gura/README.md
          mv ./gura/static/DOCS.md ./gura/README.md
          v doc -m -f html ./gura
          mv ./gura/_docs/gura.html ./gura/_docs/index.html
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gura/_docs/
