name: Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout VSL
        uses: actions/checkout@v2
        with:
          path: gura

      - name: Setup V
        uses: vlang/setup-v@v1
        with:
          check-latest: true

      - name: V doctor
        run: v doctor

      - name: Build docs
        run: |
          pushd gura
          rm -f README.md
          mv static/DOCS.md README.md
          v doc -readme -m -f html .
          popd

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gura/_docs/
