name: Validate Docs

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
      - name: Checkout vgura
        uses: actions/checkout@v2
        with:
          path: vgura
      - name: Build V
        run: |
          make
          sudo ./v symlink
      - name: V doctor
        run: v doctor
      - name: Validate docs
        run: |
          v install jware-solutions.vgura
          cd vgura
          v check-md .
