name: Validate Docs

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
      - name: Checkout vgura
        uses: actions/checkout@v2
        with:
          path: vgura
      - name: Build V
        run: |
          make
          sudo ./v symlink
      - name: V doctor
        run: v doctor
      - name: Move vgura source code to V Modules
        run: |
          mkdir ~/.vmodules/gura_conf
          mv ./vgura ~/.vmodules/gura_conf
      - name: Validate docs
        run: |
          cd ~/.vmodules/gura_conf/vgura
          v check-md .
